// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGsia8gNVh9BI0HIKhhjebZnYwaowuLB0',
    appId: '1:141245033510:web:2ee7bf8d045f3a03d0cae7',
    messagingSenderId: '141245033510',
    projectId: 'psm-prjct',
    authDomain: 'psm-prjct.firebaseapp.com',
    storageBucket: 'psm-prjct.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7-QFNXIj9NhMHi8kE97x4Jir85kDFcSY',
    appId: '1:141245033510:android:7abf0f4314f124d1d0cae7',
    messagingSenderId: '141245033510',
    projectId: 'psm-prjct',
    storageBucket: 'psm-prjct.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUaWD7dp39AN2h8LrNu8G4o9CbWhAbiqU',
    appId: '1:141245033510:ios:281f2fbcd6720c27d0cae7',
    messagingSenderId: '141245033510',
    projectId: 'psm-prjct',
    storageBucket: 'psm-prjct.firebasestorage.app',
    iosBundleId: 'com.PsmProg.psm',
  );
}
